---
# Playbook to validate the chrome installation
# Here we are checking the chrome installtion below path
# HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome
# If systems are customized we mention the path based on system
# To install chrome we are downloading exe file from below path
# http://dl.google.com/chrome/install/375.126/chrome_installer.exe
# If we want to get the latest version please find and replace the latest url by using a variable chrome_url
# We can replace the destination path by using a variable chrome_dst
# Playbook will fail if not able to download the exe file with error message

- name: Verify Google Chrome installation
  hosts: all
  gather_facts: true
  vars:
    chrome_url: http://dl.google.com/chrome/install/375.126/chrome_installer.exe
    chrome_dst: C:\Temp\chrome_installer.exe
  tasks:
    - name: Check if Google Chrome is already installed
      win_command: 'wmic datafile where "Name='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'" get Version /value'
      register: chrome_installed

    - name: Print installed Google Chrome version
      debug:
        msg: "Google Chrome is already installed with version {{ chrome_installed.stdout.Version }} on {{ inventory_hostname }}"
      when: chrome_installed.rc == 0

    - name: Print hosts if not installed Google Chrome
      debug:
        msg: "Google Chrome is not installed on {{ inventory_hostname }}"
      when: chrome_installed.rc == 0
      
    - name: Download Google Chrome exe
      win_get_url:
        url: "{{ chrome_url }}"  # Replace with needed version url and Make sure host have access to the internet
        dest: "{{ chrome_dst }}"
      register: download_result
      ignore_errors: true
      when: chrome_installed.rc != 0
      
    - name: Print and fail the execution if not able to download
      fail:
        msg: "Not able to download Please download manually and copy to the host"
      when:
        - chrome_installed.rc != 0
        - downlaod_result.rc != 0

    - name: Install Google Chrome
      win_command: 'C:\Temp\chrome_installer.exe /silent /install'
      register: install_status
      when:
        - chrome_installed.rc != 0
        - downlaod_result.rc == 0
        
    - name: Print hosts if downloaded and installed Google Chrome
      debug:
        msg: "Google Chrome downloaded and installed on {{ inventory_hostname }}"
      when:
        - chrome_installed.rc != 0
        - download_result.rc == 0
